### ISSUE TITLE
Crash at "by deck" and "show all games" tab

### ISSUE THREAD

**Issue by kingbrucelee** [keluokeda/hs_tracker#6]
Error log of "by deck" tab
```
java.lang.ArithmeticException: divide by zero
	at com.ke.hs_tracker.module.ui.summary.BattleRateItem$DeckBattleRate.getRate(BattleRateItem.kt:67)
	at com.ke.hs_tracker.module.ui.summary.BattleRateListFragment$onViewCreated$lambda-3$lambda-2$$inlined$sortedByDescending$1.compare(Comparisons.kt:321)
	at java.util.TimSort.countRunAndMakeAscending(TimSort.java:355)
	at java.util.TimSort.sort(TimSort.java:220)
	at java.util.Arrays.sort(Arrays.java:1427)
	at kotlin.collections.ArraysKt___ArraysJvmKt.sortWith(_ArraysJvm.kt:2557)
	at kotlin.collections.CollectionsKt___CollectionsKt.sortedWith(_Collections.kt:1073)
	at com.ke.hs_tracker.module.ui.summary.BattleRateListFragment$onViewCreated$lambda-3$$inlined$collect$1.emit(Collect.kt:142)
	at kotlinx.coroutines.flow.StateFlowImpl.collect(StateFlow.kt:398)
	at kotlinx.coroutines.flow.StateFlowImpl$collect$1.invokeSuspend(Unknown Source:15)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:234)
	at kotlinx.coroutines.DispatchedTaskKt.resumeUnconfined(DispatchedTask.kt:190)
	at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:161)
	at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:397)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:431)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(CancellableContinuationImpl.kt:420)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.kt:328)
	at kotlinx.coroutines.flow.StateFlowSlot.makePending(StateFlow.kt:286)
	at kotlinx.coroutines.flow.StateFlowImpl.updateState(StateFlow.kt:351)
	at kotlinx.coroutines.flow.StateFlowImpl.setValue(StateFlow.kt:318)
	at com.ke.mvvm.base.ui.BaseContentViewModel.showContent(BaseContentViewModel.kt:29)
	at com.ke.hs_tracker.module.ui.summary.BattleRateListViewModel.access$showContent(BattleRateListViewModel.kt:11)
	at com.ke.hs_tracker.module.ui.summary.BattleRateListViewModel$refresh$1.invokeSuspend(BattleRateListViewModel.kt:24)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.app.ActivityThread.main(ActivityThread.java:8272)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)

```

**Comment by kingbrucelee** [comment]
Any updates?
